Action demo mvi
ibm-build-lab/VAD-VAR-Workshop pull request #170
Opened 2023-07-12 16:51 UTC by adelineliou

Created MD file for action detection demo

Added MVI-action attachments containing images for the demo walkthrough as well as pre-trained Action detection model Zip and Pre-created dataset zips.

2023-07-14 15:39 UTC, Hans-J-Klose requested changes
Please review my comments.

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +2. The **Data sets**window opens.
Need a space after sets

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +
Should add a section that talks about downloading, unzipping, and using provided videos if they wish to use those.

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +In this step, you will label the water bottle videos. Labeling is marking the input videos with information about its contents. In action detection, this would involve highlighting start and end time
Remove squeezing

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +As a first step towards building your AI inspection model, you must create a dataset in MVI containing videos of twisting on and off the caps of water bottles, shaking water bottles, and squeezing wa
Remove squeezing

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +In this step, you will label the water bottle videos. Labeling is marking the input videos with information about its contents. In action detection, this would involve highlighting start and end time
I think it should also be `labeled` instead of `labelled`

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +Now that you have a workable dataset of videos, as the Asset Analyst, it’s time to train an action detection model in MVI using these labelled videos. Training is the process of fitting a model to th
I think it should be `labeled` instead of `labelled`

2023-07-14 15:39 UTC, Hans-J-Klose commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +
Again, maybe add a section to talk about downloading, unzipping, and utilizing the pre-recorded untrained videos if they prefer.

2023-07-17 16:14 UTC, Hans-J-Klose approved these changes

2023-07-18 23:32 UTC, adams0619 reviewed
@adelineliou This is a great detailed write up with lots of visual cues, thanks for making this addition.

I left a few _(mostly minor)_ comments, but I wanted to note that the bigger thing the teams needs too address is finding a better solution for hosting some of these larger files. While not a something that needs to be addressed in this PR, just wanted to point it out since pulling down this PR takes little bit of time.

2023-07-18 23:32 UTC, adams0619 commented on content/Maximo/VISUAL-INSPECTION-ACTION.md
> +![](_attatchments/mvi-action/MVI-action-detection-Step2.9.png)
**content**: this image doesn't exist

2023-07-19 15:13 UTC, Hans-J-Klose approved these changes
LGTM

2023-07-19 19:36 UTC, adams0619 approved these changes

2023-07-19 21:47 UTC, merged