Kris prompt engineering
ibm-build-lab/VAD-VAR-Workshop pull request #184
Opened 2023-09-14 19:05 UTC by krisyifanyang

This is prompt engineering branch based on RR-Watson Data branch

2023-09-15 18:37 UTC, maurelya requested changes

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +```
add the word `text` after ``` to fix the formatting I see on the webpage: 
<img width="922" alt="Screenshot 2023-09-15 at 2 00 16 PM" src="https://github.com/ibm-build-lab/VAD-VAR-Workshop/assets/19367627/b60202c6-a4d9-41ee-ac72-f5a4cedee3e0">

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +```
add the word text after ``` to fix the formatting

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +With great artificial intelligence comes higher security risks. Solutions like ChatGPT are Very Large language Models (VLLMs) with 175 billion parameters. They fine-tuned by the OpenAI team using an
This is well-written.

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +```
For the following exercises add the word `text` after ``` to fix the formatting

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +See: [Example answer](109.md#1-generate)
I am having issues going to the example answer page.
I am able to render the page if I include the full path `/watsonx/watsonxai/109#1-generate` like this

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +See: [Example answer](109.md#2-rewrite)
`/watsonx/watsonxai/109#2-rewrite`

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +See: [Example answer](109.md#3-summarize)
`/watsonx/watsonxai/109#3-summarize`

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +See: [Example answer](109.md#4-text-extraction)
`/watsonx/watsonxai/109#4-text-extraction`

2023-09-15 18:37 UTC, maurelya commented on content/Watsonx/WatsonxAI/101.md
> +# Lab 101: Prompt engineering
When you are done editing the md files written in English, create new md files written in Spanish.
You can use Jake's [script](https://github.com/jbukuts/markdown-translate) to translate the md files

2023-09-19 16:22 UTC, ridgill commented
Looks like this branch also contains all the changes from Rakesh's data lab.  Need to remove those commits before merging.  This branch should contain only the watsonx ai prompt lab content.

2023-09-19 19:12 UTC, krisyifanyang commented
> Looks like this branch also contains all the changes from Rakesh's data lab. Need to remove those commits before merging. This branch should contain only the watsonx ai prompt lab content.

I will rebase based on the master

2023-09-21 16:53 UTC, krisyifanyang commented on content/Watsonx/WatsonxAI/101.md
> +# Lab 101: Prompt engineering
we should direct them to the watsonx main page then create a project then we can see the prompt lab, but fyi it is here dataplatform.cloud.ibm.com/wx

2023-09-21 19:17 UTC, ridgill commented
newer PR opened

2023-09-21 19:17 UTC, closed without merging