watsonx.ai L4 lab - Introduction to Generative AI
ibm-build-lab/VAD-VAR-Workshop pull request #323
Opened 2024-02-09 19:38 UTC by maurelya

Fixes https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/316

Content changes:

- Any content updates here

Code changes:

- Any code changes here

2024-02-09 22:57 UTC, r2raman requested changes
Just checking if we can use jupiter hub to execute the python code.

2024-02-09 22:57 UTC, r2raman commented on content/Watsonx/WatsonxAI/201.md
> +    Example of token limits (from documentation):
Keep 1 line gap between the last bullet and the start of the paragraph.

2024-02-09 22:57 UTC, r2raman commented on content/Watsonx/WatsonxAI/201.md
> +    Now that you have reviewed and created prompts, we will test the integration of LLMs with
Keep 1 line gap between the last bullet and the start of the paragraph.

2024-02-10 16:23 UTC, maurelya commented
> Just checking if we can use jupiter hub to execute the python code.

The Python scripts use the Streamlit library to open a page in the web browser.
It’s not currently possible to run Streamlit inside Jupyter. https://discuss.streamlit.io/t/running-streamlit-in-a-jupyter-cell/584

2024-02-10 20:36 UTC, r2raman approved these changes

2024-02-10 20:36 UTC, merged