feat(.gov): add level 4 lab 203
ibm-build-lab/VAD-VAR-Workshop pull request #398
Opened 2024-06-21 12:19 UTC by krab7191

Closes https://github.com/ibm-build-lab/vest-content/issues/142

Content changes:

- Add Level 4 subfolder with basic lab files
- Add 203 lab & screenshots

Code changes:

- Any code changes here

2024-06-21 12:20 UTC, krab7191 commented
NOTE: I felt there were too many repetitive steps and so compressed a lot. Waiting for my new TZ reservation to finish so I can get new screenshots.

2024-06-25 21:28 UTC, MaxShapiro32 requested changes

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    6. Click on the **Default owner** dropdown and select the **admin** user, then click Apply. You will return to the previous screen.
`Apply` -> `**Apply**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    8. On the **Sync with Governance console (IBM OpenPages)** page, click on the **OpenPages location** dropdown and select IBM Cloud Pak for Data. Note that, depending on the version you have, this
`IBM Cloud Pak for Data` -> `**IBM Cloud Pak for Data**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    8. At the top of the table, click the **Edit** button, <br />![role templates edit](../images/203/watsonxgov-l4_role-templates-edit.webp) and then change the **Write**, **Delete**, and **Associat
`Click Done` -> `Click **Done**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    3. Click the **Create a database** button, and verify that the **Db2** tile is selected as the database type, with the most recent software version selected in the dropdown. Click Next to continu
`Click Next` -> `Click **Next**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    4. Under **Storage option**, make sure **Single location for all data** is selected, and click next. ![create db configure](../images/203/watsonxgov-l4_create-db-configure.webp) Keep the defaults
`Click Next` -> `Click **Next**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    5. Under credentials, use the **Input method** dropdown to select **Generate a Kubernetes secret** and click next. <br />![create db creds](../images/203/watsonxgov-l4_create-db-creds.webp)
`Click Next` -> `Click **Next**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    6. For Storage, select **Create new storage**, **Use storage template**, and in the dropdown select **ocs-storagecluster-cephfs**. Reduce the size to **50 GiB** and click next. <br /> ![create db
`Click Next` -> `Click **Next**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    7. On the Finalize screen, you can safely ignore the warning message. Set the Display name to `cpd-database` and click Create. The database will take roughly 30 minutes to create. When it is fini
`click Create` -> `click **Create**`
`30 minutes` -> `**30 minutes**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    2. Locate the **IBM Watson OpenScale instance** from the list. Note that, on IBM Cloud, this service has been renamed to watsonx.governance. Future software releases will likely incorporate this
Make the Note a `> NOTE`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    7. Click Connect. The monitoring service will attempt to connect to the database using the credentials you supplied. If the connection fails, double-check that you have constructed the hostname c
`Click Connect` -> `Click **Connect**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    1. From the CP4D home screen use the hamburger menu, then **services** -> **Instances**
`**services**` -> `**Services**`

2024-06-25 21:28 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    3. Click on **Add users**, then select the user you created, and set the role to Admin, then click add. <br /> ![openscale user add](../images/203/watsonxgov-l4_openscale-user-add.webp) <br />The
`Admin` -> `**Admin**`
`click add` -> `click **add**`

2024-06-26 16:26 UTC, krab7191 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +3. Click the blue **Add users** button, and then fill out the profile information. Make sure not to forget your username or password! Click **Next**. <br />![user details](../images/203/watsonxgov-l4
Ah ok. Will fix up

2024-06-26 17:18 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    3. Click on **Add users**, then select the user you created, and set the role to **Admin**, then click **add**. <br /> ![openscale user add](../images/203/watsonxgov-l4_openscale-user-add.webp) <
This screenshot should be updated to show the `complianceofficer` username to be consistent

`then select the user you created` can specify `complianceofficer`

2024-06-26 17:18 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +3. Click the blue **Add users** button, and then fill out the profile information. Use `complianceofficer` for the username, as this will be referenced in future labs. Make sure not to forget your pa
This screenshot should be updated to show the `complianceofficer` username to be consistent

2024-06-26 17:18 UTC, MaxShapiro32 commented on content/Watsonx/WatsonxGov/Level-4/203.md
> +    12. On the **Set collaborators** page, click **Add collaborators**, then **Add user**, and start typing the user ID of the user you created to find it. Make sure **Admin** is selected, then click
These screenshots should be updated to show the `complianceofficer` username to be consistent

`start typing the user ID of the user you created` can specify `complianceofficer`

2024-06-26 17:18 UTC, MaxShapiro32 approved these changes

2024-06-26 22:05 UTC, merged